### ISSUE TITLE
TYPO3 10 Compability

### ISSUE THREAD

**Issue by jsegars** [xperseguers/t3ext-cloudflare#7]
Are there any plans/timelines for TYPO3 10 compatibility?  I see one commit related to v10.  From a quick test here, the only things I've discovered are are the composer.json file and a tiny fix in the DashboardController's constructor.

It's my first time using the extension, so this was far from comprehensive.  I'm curious if there's anything else you're aware of or if that may be it.

**Comment by msollmann** [comment]
Any news on this?

**Comment by xperseguers** [comment]
Hello. I'm not yet in need of this extension under TYPO3 v10 so to be honest I just did not work on it anymore since the first commit for compatibility with v10. If that's really a must-have for you, feel free to open explicit tickets with stuff that break under v10 and possibly provide PR as well.

I shall work on it at some point but cannot say right now "when".

**Comment by benabbottnz** [comment]
FYI I've forked this project and made it work under TYPO3 10 if anyone is interested in seeing what was changed: https://github.com/ocular-nz/t3ext-cloudflare

Please note my changes aren't intended to be pulled back into this upstream repo so there's a couple changes in there you probably wouldn't want, like removing consideration for backwards compatibility.

Not much needs to be done to make this work in TYPO3 v10.

**Comment by fabarea** [comment]
FYI, I have successfully tested the @benabbottnz fork, and it works nicely.

**Comment by xperseguers** [comment]
Indeed, just had a look of a diff between your fork and current master and there's nearly nothing to do to make it compatible with v10 while keeping (some) backward compatibility.

**Comment by xperseguers** [comment]
master branch is compatible with TYPO3 v10.
